sudo: required

language: python
python:
- '3.6'

# Make release trigged by a tagged commit
deploy:
    provider: releases
    api_key:
        secure: $DEPLOYMENT_KEY
    script: bash paking_script.sh
    file:
        - packs/myawesomegame-1.0.1-1.i386.rpm
        - packs/myawesomegame-1.0.1-1.x86_64.rpm
        - packs/myawesomegame_1.0.1-1_amd64.deb
        - packs/myawesomegame_1.0.1-1_i386.deb
    skip_cleanup: true
    on:
        repo: $REPO_NAME
        branch: empacotamento
        tags: true

